application: csce242-gmesalazar
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: csce242.app
  
libraries:
- name: jinja2
  version: latest