application: csce242-gmesalazar
version: 6
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /templates/stylesheets
  static_dir: templates/stylesheets
  
- url: /templates/images
  static_dir: templates/images

- url: /templates/js
  static_dir: templates/js

- url: /.*
  script: csce242.app
  
libraries:
- name: jinja2
  version: latest