application: csce242-gmesalazar
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /templates/stylesheets
  static_dir: templates/stylesheets

- url: /.*
  script: csce242.app
  
libraries:
- name: jinja2
  version: latest